CREATE TABLE `pet` (
  `ID_PET` int NOT NULL AUTO_INCREMENT,
  `NOME` varchar(45) DEFAULT NULL,
  `MATRICULA` varchar(45) NOT NULL,
  `RACA` varchar(45) DEFAULT NULL,
  `ID_CLIENTE` int DEFAULT NULL,
  PRIMARY KEY (`ID_PET`),
  KEY `PET_CLIENTE_idx` (`ID_CLIENTE`),
  CONSTRAINT `PET_CLIENTE` FOREIGN KEY (`ID_CLIENTE`) REFERENCES `cliente` (`ID_CLIENTE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;